# Generated by Django 4.0.2 on 2022-04-18 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_x', models.IntegerField(blank=True, null=True)),
                ('loc_y', models.IntegerField(blank=True, null=True)),
                ('ups_account', models.TextField(blank=True, default='')),
                ('card_number', models.DecimalField(blank=True, decimal_places=0, max_digits=16, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
